name: CI
on:
  push:
    branches: [ "main", "switch-to-actions" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Install Racket
        uses: Bogdanp/setup-racket@v0.11
        with:
          architecture: 'x64'
          distribution: 'full'
          variant: 'CS'
          version: 'stable'
      - name: Build deps
        run: make deps
      - name: Build app
        run: make build_unix
      - name: Test
        run: make test

